name: Run application
run-name: 🚀
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  Run:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.VODOVOD_USER }}
        run: |
          echo "$SUPER_SECRET"
      - run: npm i
      - run: npm start
        env:
          VODOVOD_USER: "${{ secrets.VODOVOD_USER }}"
          VODOVOD_PASS: "${{ secrets.VODOVOD_PASS }}"
          TEST_ME: "${{ vars.TEST_ME }}"
