name: Run application
run-name: 🚀
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm start
